engines:
  eslint:
    enabled: true
ratings:
  paths:
    - "Resources/Private/JavaScript/**"
exclude_paths:
 - "package.json"
 - "karma.conf.js"
 - "karma.entry.js"
 - "wdio.config.js"
 - "webpack.config.js"
 - "Build/**/*"
 - "Tests/**/*"
