sudo: false
language: node_js
notifications:
  email: false

#
# Cache the node_modules directory to speed up the the installation of dependencies.
#
cache:
  directories:
    - node_modules

#
# Parallel environments, the value represents the name of the shell script which needs to be placed in `Build/TravisCi/Scripts/[name].sh`.
#
env:
  - TEST_SUITE=CodeStyle
  - TEST_SUITE=UnitTests

#
# Prune the node_modules to remove extranous packages from previous/cached runs.
#
before_install:
  - npm prune

#
# Install and setup the neos instance.
#
install:
  # Execute the test environment specific `install` shell script.
  - if [ -f "Build/TravisCi/InstallScripts/$TEST_SUITE.sh" ]; then bash Build/TravisCi/InstallScripts/$TEST_SUITE.sh; fi

script:
  # Execute the test environment specific `script` shell script.
  - if [ -f "Build/TravisCi/Scripts/$TEST_SUITE.sh" ]; then bash Build/TravisCi/Scripts/$TEST_SUITE.sh; fi

#
# Execute the test environment specific `after_script` shell script.
#
after_script:
  - if [ -f "Build/TravisCi/AfterScripts/$TEST_SUITE.sh" ]; then bash Build/TravisCi/AfterScripts/$TEST_SUITE.sh; fi
