sudo: false
notifications:
  email: false
language: node_js

#
# Cache the composer and node_modules directory to speed up the the installation of dependencies.
#
cache:
  directories:
    - node_modules

#
# Execute the test environment specific shell script.
#
script:
  - npm run lint
  - npm run karma

#
# Publish the code coverage as soon as the test finsihed.
#
after_script:
  - npm install -g codeclimate-test-reporter
  - mv Coverage/**/lcov.info
  - if [ -n "$CODECLIMATE_REPO_TOKEN" ]; then codeclimate-test-reporter < lcov.info; fi;
