sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  # - npm i -g codeclimate-test-reporter
before_script:
  - npm prune
script:
  - npm run lint
  - npm run karma
after_script:
  # - codeclimate-test-reporter < coverage/lcov.info
