TYPO3:
  Flow:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              controllerObjectName: 'Neos\Neos\Ui\Controller\.*|TYPO3\Neos\Controller\.*|TYPO3\Neos\Service\.*|TYPO3\Media\Controller\.*'
  Neos:
    typoScript:
      autoInclude:
        'Neos.Neos.Ui': TRUE

  TypoScript:
    defaultContext:
      'Neos.Ui.Activation': 'Neos\Neos\Ui\TypoScript\Helper\ActivationHelper'

Neos:
  Neos:
    Ui:
      # All PRIVATE, not meant for public extensibility.
      state:
        defaultEelContext:
          String: 'TYPO3\Eel\Helper\StringHelper'
          Array: 'TYPO3\Eel\Helper\ArrayHelper'
          Date: 'TYPO3\Eel\Helper\DateHelper'
          Configuration: 'TYPO3\Eel\Helper\ConfigurationHelper'
          Math: 'TYPO3\Eel\Helper\MathHelper'
          Json: 'TYPO3\Eel\Helper\JsonHelper'
          I18n: 'TYPO3\Flow\I18n\EelHelper\TranslationHelper'
          'Neos.Ui.Workspace': 'Neos\Neos\Ui\TypoScript\Helper\WorkspaceHelper'
          'Neos.Ui.NodeInfo': 'Neos\Neos\Ui\TypoScript\Helper\NodeInfoHelper'
          'Neos.Ui.NodeTypes': 'Neos\Neos\Ui\TypoScript\Helper\NodeTypesHelper'

        documentNode:
          nodes: '${Neos.Ui.NodeInfo.renderDocumentNodeAndChildContent(documentNode, controllerContext)}'
          metaData:
            contextPath: '${q(documentNode).property("_contextPath")}'
            previewUrl: '${Neos.Ui.NodeInfo.uri(q(documentNode).context({workspaceName: "live"}).get(0), controllerContext)}'
        backend:
          changes:
            pending: []
            processing: []
            failed: []
          cr:
            nodeTypes:
              byName: ${Neos.Ui.NodeTypes.nodeTypesByName()}
              constraints: ${Neos.Ui.NodeTypes.nodeTypeConstraints()}
              inheritanceMap: ${Neos.Ui.NodeTypes.nodeTypeInheritanceMap()}
              groups: ${Configuration.setting('TYPO3.Neos.nodeTypes.groups')}
            nodes:
              byContextPath: ${Neos.Ui.NodeInfo.defaultNodesForBackend(site, documentNode, controllerContext)}
              siteNode: ${q(site).property('_contextPath')}
            workspaces:
              byName: ${Neos.Ui.Workspace.initializeWorkspacesByName()}
              active: ${Neos.Ui.Workspace.getPersonalWorkspaceName()}
          ui:
            contentCanvas:
              src: ${Neos.Ui.NodeInfo.uri(documentNode, controllerContext)}
              contextPath: ${q(documentNode).property('_contextPath')}
            debugMode: false
            fullScreen:
              isFullScreen: false
            leftSideBar:
              isHidden: false
            rightSideBar:
              isHidden: false
            addNodeModal:
              referenceNode: ''
              mode: 'insert'
            drawer:
              isHidden: true
            pageTree:
              isLoading: false
              hasError: false
              focused: ${q(documentNode).property('_contextPath')}
              active: ${q(documentNode).property('_contextPath')}
            remote:
              isSaving: FALSE
              isPublishing: FALSE
              isDiscarding: FALSE
          user:
            name:
              title: ${q(user).property('name.title')}
              firstName: ${q(user).property('name.firstName')}
              middleName: ${q(user).property('name.middleName')}
              lastName: ${q(user).property('name.lastName')}
              otherName: ${q(user).property('name.otherName')}
              fullName: ${q(user).property('name.fullName')}
            settings:
              isAutoPublishingEnabled: false

      changes:
        types:
            'Neos.Neos.Ui:Property': 'Neos\Neos\Ui\Domain\Model\Changes\Property'
            'Neos.Neos.Ui:Create': 'Neos\Neos\Ui\Domain\Model\Changes\Create'
            'Neos.Neos.Ui:CreateBefore': 'Neos\Neos\Ui\Domain\Model\Changes\CreateBefore'
            'Neos.Neos.Ui:CreateAfter': 'Neos\Neos\Ui\Domain\Model\Changes\CreateAfter'
